### PR TITLE
Rev from QT5.15.1 to QT5.15.2

### PR DESCRIPTION
**Pull request by jhoyt4**
#### Description

rebase to macports-port master and rev qt to qt15.5.2

###### Type(s)

- [X] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 11.0.1 20B29
Xcode 12.2 12B45b

### CODE REVIEW

**Comment by jhoyt4** [comment]
...not sure why this is failing CI/build.  The logs leave a lot to be desire...

**Comment by michaelld** [comment]
@jhoyt4 Does this PR piggyback off of https://github.com/macports/macports-ports/pull/8744 (the Qt5 update from 5.14.2 to 5.15.1)?

**Comment by michaelld** [comment]
> @jhoyt4 Does this PR piggyback off of [macports#8744](https://github.com/macports/macports-ports/pull/8744) (the Qt5 update from 5.14.2 to 5.15.1)?

No, it does not. Next question, which is hopefully a better question: Does this PR incorporate all of the various tweaks and fixes discussed in the other PR? There are so many files changed it's really hard to track down and determine what's going on!

**Comment by michaelld** [comment]
Ah ... OK I see ... it's with respect to my repo's master ... got it! OK I understand how to work with this then. My question about what is in this PR remains ...

**Comment by jhoyt4** [comment]
> My question about what is in this PR remains ...


> > @jhoyt4 Does this PR piggyback off of [macports#8744](https://github.com/macports/macports-ports/pull/8744) (the Qt5 update from 5.14.2 to 5.15.1)?
> 
> No, it does not. 

Actually it does.  I piggybacked off of you 5.15.1 worke, rebaselined to the lastest macport (now dated), modified your Portfile to incorporate the correct checkums for 5.15.2, added the two patches to get this working on Big Sur and commented out one or two current patches that broke with the update to 5.15.2.

Feel free to ignore the PR and take whatever you want from the patches I posted on your PR.

**Comment by jhoyt4** [comment]
...made things too complicated

**Comment by jhoyt4** [comment]
...you may also want this patch to get qtquick3d to compile (flag no longer works / nor is necessary)

[qtquick3d](https://github.com/jhoyt4/macports-ports/commit/a5c50ed7217b63ba6d28b3aac5a3bab172af2bfd#diff-bc9f30dc8c9f361f400189b91801321d634f45c504735b63dd156a06e245449f)

**Comment by jhoyt4** [comment]
> Ah ... OK I see ... it's with respect to my repo's master 

Crud - I could have sworn I did this off of your "qt5: update to 5.15.1" repo.  Apologies for the confusion...  At any rate, to get your 5.15.1 working (at least on Big Sur) you need these files to get it working (based off of your 5.15.1 work)

[qt5.zip](https://github.com/michaelld/macports-ports/files/5615554/qt5.zip)

**Pull request closed without merging**
